
name: Build FXGL runtime using JavaFX Maven Plugin

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  linux-build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: oracle-actions/setup-java@v1
        with:
          website: jdk.java.net
          release: 18
      - name: Build with Maven
        run: mvn javafx:jlink
      - uses: actions/upload-artifact@v2
        with:
          name: linuxrt
          path: /home/runner/work/fxgl-runtime/fxgl-runtime/target/app.zip
          retention-days: 1

  mac-build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: oracle-actions/setup-java@v1
        with:
          website: jdk.java.net
          release: 18
      - name: Build with Maven
        run: jlink --strip-debug --compress 1 --no-header-files --no-man-pages --output jre --add-modules java.base,java.desktop,java.instrument,java.logging,java.prefs,jdk.unsupported
      - uses: actions/upload-artifact@v2
        with:
          name: macosxrt
          path: /Users/runner/work/fxgl-runtime/fxgl-runtime/target/app.zip
          retention-days: 1

  win-build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: oracle-actions/setup-java@v1
        with:
          website: jdk.java.net
          release: 18
      - name: Build with Maven
        run: mvn javafx:jlink
      - uses: actions/upload-artifact@v2
        with:
          name: windowsrt
          path: D:\a\fxgl-runtime\fxgl-runtime\target\app.zip
          retention-days: 1
