
name: Build FXGL runtime using JavaFX Maven Plugin

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  mac-build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: oracle-actions/setup-java@v1
        with:
          website: jdk.java.net
          release: 18
      - name: Build with Maven
        run: jlink --strip-debug --compress 1 --no-header-files --no-man-pages --output jre --add-modules java.base,java.desktop,java.instrument,java.logging,java.prefs,jdk.unsupported
      - name: Show Path
        run: pwd
      - name: Tar
        run: tar -zcvf jre.tar.gz jre
      - name: Chmod
        run: chmod 777 jre.tar.gz jre
      - uses: actions/upload-artifact@v2
        with:
          name: macosxrt
          path: /Users/runner/work/fxgl-runtime/fxgl-runtime/jre.tar.gz
          retention-days: 1
